### ISSUE TITLE
Unable to program QSPI flash

### ISSUE THREAD

**Issue by whik** [quartiq/bscan_spi_bitstreams#11]
Hello, sir,

I am using Jlink to program Xilinx XC7K325T FPGA. It is successful to program BIT file through openocd. It is also possible to program SPIx1 BIN file, but the program cannot run when program SPIx4 BIN file. Excuse me xc7_bscan_spi.bit file support QSPI flash program?

Thanks!

**Comment by jordens** [comment]
The proxy bitstreams only support one-bit spi, not qspi.
