### ISSUE TITLE
Unable to geneated bscan_spi_xc6slx9t.bit

### ISSUE THREAD

**Issue by Dv-p** [quartiq/bscan_spi_bitstreams#15]
Hello !!

I followed README and executed command but it's having error while building bscan_spi_xc6slx9t.bit but other bit files are generating properly. Also I tried finding this in master and their branches but I couldn't found it.

![Screenshot from 2024-03-16 15-23-44](https://github.com/quartiq/bscan_spi_bitstreams/assets/146713273/7da33c58-22cf-49a3-bcd9-4734d3172706)

Can you help me with this? Or provide me this bit file, that would be much helpful.

Thanks !!

**Comment by jordens** [comment]
You'll have to read the full log.

**Comment by Dv-p** [comment]
Thanks for the reply !!
I read log file. It says invalid target device 'xc6slx9t'. Attaching log file for your reference.

[xc6slx9t_log.txt](https://github.com/quartiq/bscan_spi_bitstreams/files/14623282/xc6slx9t_log.txt)

Is there any solution for this ?

**Comment by jordens** [comment]
I don't know. Maybe the device doesn't exist.

**Comment by Dv-p** [comment]
Okay I built it in different way. Not an issue.
Basically I am trying to flash my spartan6 (xc6slx9t) using openocd via jtag. I am able to program my spratan6 but unable to flash it, below is the snapshot of the error:
![openocd_error](https://github.com/quartiq/bscan_spi_bitstreams/assets/146713273/2c3775ef-5e9f-49ad-aa8b-f6fda932426d)

Using following command:
`openocd -f /usr/local/share/openocd/scripts/interface/raspberrypi-native.cfg -f /usr/local/share/openocd/scripts/cpld/xilinx-xc6s.cfg -f /usr/local/share/openocd/scripts/cpld/jtagspi.cfg -c "init; jtagspi_init 0 ./Downloads/bscan_spi_xc6slx9t.bit; jtagspi_program ./Desktop/topgcspihostmot2.bin 0; xc6s_program xc6s.tap; shutdown"`

Can you help me with this ?

Thanks !!

**Comment by jordens** [comment]
How did you build.it of the device isn't recognized?

It looks like it can't talk to the flash chip. Maybe wrong pin out.

**Comment by Dv-p** [comment]
I built it using ISE Design suite (using generated .v and .ucf files). Also I am able to flash now, pin assignement was right, issue was in command.

**Comment by jordens** [comment]
Could you check what's wrong and why it doesn't build using the existing script? Maybe there's an easy fix.

**Comment by Dv-p** [comment]
Sorry I don't have that much scripting knowledge. That was the reason I raised the issue.
